version: "3.9"

services:
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      GATEWAY_API_KEY: "client-secret-key"
      DISPATCHER_PROXY_HOST: envoy
      DISPATCHER_PROXY_PORT: "50051"
      DISPATCHER_API_KEY: "dispatcher-secret-key"
      RABBIT_HOST: rabbitmq
      TASK_QUEUE: tasks_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
      envoy:
        condition: service_started
    networks:
      - app_net



  envoy:
    image: envoyproxy/envoy:v1.32.6
    container_name: envoy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    ports:
      - "50051:50051"   # Gateway - Envoy - Dispatcher
      - "50052:50052"   # Dispatcher - Envoy - Worker
      - "9901:9901"     # admin UI
    depends_on:
      - dispatcher
      - worker
    networks:
      - app_net


  dispatcher:
    build:
      context: ./dispatcher
    container_name: dispatcher
    environment:
      DISPATCHER_PORT: "50051"
      DISPATCHER_API_KEY: "dispatcher-secret-key"
      WORKER_PROXY_HOST: envoy
      WORKER_PROXY_PORT: "50052"
      WORKER_API_KEY: "worker-secret-key"
      DISPATCHER_LOG: "/logs/dispatcher_logs.jsonl"
    expose:
      - "50051"
    depends_on:
      - worker
    volumes:
      - ./logs:/logs
    networks:
      - app_net

  async_dispatcher:
    build:
      context: ./async_dispatcher
    container_name: async_dispatcher
    environment:
      RABBIT_HOST: rabbitmq
      TASK_QUEUE: tasks_queue
      DISPATCHER_LOG: "/logs/dispatcher_async_logs.jsonl"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net
    volumes:
      - ./logs:/logs

  worker:
    build:
      context: ./worker
    container_name: worker
    environment:
      WORKER_PORT: "50052"
      WORKER_API_KEY: "worker-secret-key"
      WORKER_LOG: "/logs/worker_logs.jsonl"
    expose:
      - "50052"
    volumes:
      - ./logs:/logs
    networks:
      - app_net

  async_worker:
    build:
      context: ./async_worker
    container_name: worker_async
    environment:
      RABBIT_HOST: rabbitmq
      TASK_QUEUE: tasks_queue
      WORKER_LOG: "/logs/worker_async_logs.jsonl"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net
    volumes:
      - ./logs:/logs

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
