# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dispatcher_pb2 as dispatcher__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispatcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DispatchNotification = channel.unary_unary(
                '/dispatcher.DispatcherService/DispatchNotification',
                request_serializer=dispatcher__pb2.DispatchNotificationDto.SerializeToString,
                response_deserializer=dispatcher__pb2.DispatchResponse.FromString,
                _registered_method=True)


class DispatcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DispatchNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DispatchNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchNotification,
                    request_deserializer=dispatcher__pb2.DispatchNotificationDto.FromString,
                    response_serializer=dispatcher__pb2.DispatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dispatcher.DispatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dispatcher.DispatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DispatchNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.DispatcherService/DispatchNotification',
            dispatcher__pb2.DispatchNotificationDto.SerializeToString,
            dispatcher__pb2.DispatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessNotification = channel.unary_unary(
                '/dispatcher.WorkerService/ProcessNotification',
                request_serializer=dispatcher__pb2.WorkerRequestDto.SerializeToString,
                response_deserializer=dispatcher__pb2.WorkerResponseDto.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessNotification,
                    request_deserializer=dispatcher__pb2.WorkerRequestDto.FromString,
                    response_serializer=dispatcher__pb2.WorkerResponseDto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dispatcher.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dispatcher.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatcher.WorkerService/ProcessNotification',
            dispatcher__pb2.WorkerRequestDto.SerializeToString,
            dispatcher__pb2.WorkerResponseDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
