# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatcher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dispatcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ispatcher.proto\x12\ndispatcher\":\n\x17\x44ispatchNotificationDto\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06sentAt\x18\x02 \x01(\x03\"h\n\x10WorkerRequestDto\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06sentAt\x18\x02 \x01(\x03\x12\x16\n\x0enotificationId\x18\x03 \x01(\t\x12\x1b\n\x13\x64ispatcherStartedAt\x18\x04 \x01(\x03\"m\n\x11WorkerResponseDto\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0enotificationId\x18\x02 \x01(\t\x12\x13\n\x0bprocessedAt\x18\x03 \x01(\x03\x12\x1a\n\x12workerProcessingMs\x18\x04 \x01(\x03\"\x8c\x01\n\x10\x44ispatchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0enotificationId\x18\x02 \x01(\t\x12\x1e\n\x16\x64ispatcherProcessingMs\x18\x03 \x01(\x03\x12\x1a\n\x12workerProcessingMs\x18\x04 \x01(\x03\x12\x13\n\x0bprocessedAt\x18\x05 \x01(\x03\x32n\n\x11\x44ispatcherService\x12Y\n\x14\x44ispatchNotification\x12#.dispatcher.DispatchNotificationDto\x1a\x1c.dispatcher.DispatchResponse2c\n\rWorkerService\x12R\n\x13ProcessNotification\x12\x1c.dispatcher.WorkerRequestDto\x1a\x1d.dispatcher.WorkerResponseDtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPATCHNOTIFICATIONDTO']._serialized_start=32
  _globals['_DISPATCHNOTIFICATIONDTO']._serialized_end=90
  _globals['_WORKERREQUESTDTO']._serialized_start=92
  _globals['_WORKERREQUESTDTO']._serialized_end=196
  _globals['_WORKERRESPONSEDTO']._serialized_start=198
  _globals['_WORKERRESPONSEDTO']._serialized_end=307
  _globals['_DISPATCHRESPONSE']._serialized_start=310
  _globals['_DISPATCHRESPONSE']._serialized_end=450
  _globals['_DISPATCHERSERVICE']._serialized_start=452
  _globals['_DISPATCHERSERVICE']._serialized_end=562
  _globals['_WORKERSERVICE']._serialized_start=564
  _globals['_WORKERSERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
